[build-system]
requires = ["setuptools>=43.0"]
build-backend = "setuptools.build_meta"

[project]
name = "meerstack"
version = "0.0.1"
authors = [
  { name="Zhaoting Chen", email="ztchenustc@gmail.com" },
]
description = "A package for HI stacking using MeerKLASS"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "numpy",
    "hiimtool@git+https://github.com/zhaotingchen/hiimtool",
    "healpy",
    "matplotlib",
    "astropy",
    'scipy',
    # Conditional
    'backports.cached_property; python_version < "3.8"',
]


[project.urls]
Homepage = "https://github.com/zhaotingchen/meerstack"
Issues = "https://github.com/zhaotingchen/meerstack/issues"

[project.optional-dependencies]
test = [
    "pytest",
    "pytest-cov",
]
lint = [
    "black",
    "flake8",
    "pre-commit"
]
full = ["meerstack[test]","meerstack[lint]"]
